### ISSUE TITLE
stripe_mrr_amortized model failing due to missing mrr column

### ISSUE THREAD

**Issue by michael-erasmus** [fishtown-analytics/stripe#4]
Hey there! 

When I try running the project, I'm getting an error when trying it's building the `stripe_mrr_amortized` model:

```
04:26:56 | 18 of 24 ERROR creating view model dbt.stripe_mrr_amortized.......... [ERROR in 0.44s]
column "mrr" does not exist in events
```

I noticed that this column seems to have been removed in this commit:

https://github.com/fishtown-analytics/stripe/commit/479c2e0cc569b183d1c7f9caf194646150c14e75#diff-21cf7ee7ab72cb2c467596cfc2bea919L44

Subsequently none of the the other MRR models are building. Am I doing something wrong?

**Comment by michael-erasmus** [comment]
Just wanted to share a quick updatre. 

I managed to get around this error by checking out the 0.1.0 tag. On this tag the `stripe_stripe_mrr_amortized` models builds, but I then ran into another error when building the `dbt.stripe_mrr_discounted` model:

```
20:04:06 | 20 of 24 ERROR creating view model dbt.stripe_mrr_discounted......... [ERROR in 0.37s]
column discounts.date_day does not exist
```

**Comment by jthandy** [comment]
thanks for bringing this up! the mrr models were significantly out of date in this package. I had done a lot of work updating them in a couple of client implementations but had never genericized the code and pulled it back into the package. I just finished doing this work, and you can check out the results here:

https://github.com/fishtown-analytics/stripe/pull/5

at this point if you pull master you should be able to build working mrr tables all the way through the dependency tree. the code is rather complicated, but I can validate that we're using this logic in production currently for multiple clients and have been for 6+ months.
